package yaprnn.gui.view;

public class MainView extends javax.swing.JFrame {

    private static final long serialVersionUID = -3378803686681357347L;

    public MainView() {
        initComponents();
    }

    public javax.swing.JMenuItem getMenuSetAsNotUsed() {
        return menuSetAsNotUsed;
    }

    public javax.swing.JMenuItem getMenuSetAsTestData() {
        return menuSetAsTestData;
    }

    public javax.swing.JMenuItem getMenuSetAsTrainingData() {
        return menuSetAsTrainingData;
    }

    public javax.swing.JSlider getOptionGamma() {
        return optionGamma;
    }

    public javax.swing.JMenuItem getMenuRefresh() {
        return menuRefresh;
    }

    public yaprnn.gui.ImagePanel getLabelWeightsImage() {
        return labelWeightsImage;
    }

    public javax.swing.JComboBox getOptionZoom1() {
        return optionZoom1;
    }

    public javax.swing.JComboBox getOptionZoom2() {
        return optionZoom2;
    }

    public javax.swing.JMenuItem getMenuAdd() {
        return menuAdd;
    }

    public javax.swing.JMenuItem getMenuEdit() {
        return menuEdit;
    }

    public javax.swing.JMenuItem getMenuWebsite() {
        return menuWebsite;
    }

    public javax.swing.JTabbedPane getTabs() {
        return tabs;
    }

    public javax.swing.JMenuItem getMenuChooseRandomTrainingTestData() {
        return menuChooseRandomTrainingTestData;
    }

    public javax.swing.JMenuItem getMenuRemove() {
        return menuRemove;
    }

    public javax.swing.JSpinner getOptionOverlap() {
        return optionOverlap;
    }

    public javax.swing.JSpinner getOptionResolution() {
        return optionResolution;
    }

    public javax.swing.JTextField getLabelFilename() {
        return labelFilename;
    }

    public javax.swing.JTextField getLabelSampleLabel() {
        return labelSampleLabel;
    }

    public yaprnn.gui.ImagePanel getLabelPreviewSubsampled() {
        return labelPreviewSubsampled;
    }

    public yaprnn.gui.ImagePanel getLabelPreview() {
        return labelPreview;
    }

    public javax.swing.JTextField getLabelUsedSubsamplingOptions() {
        return labelUsedSubsamplingOptions;
    }

    public javax.swing.JMenuItem getMenuClassify() {
        return menuClassify;
    }

    public javax.swing.JMenuItem getMenuExit() {
        return menuExit;
    }

    public javax.swing.JMenuItem getMenuImportAudio() {
        return menuImportAudio;
    }

    public javax.swing.JButton getToolImportAudio() {
        return toolImportAudio;
    }

    public javax.swing.JMenuItem getMenuImportImages() {
        return menuImportImages;
    }

    public javax.swing.JButton getToolImportImages() {
        return toolImportImages;
    }

    public javax.swing.JMenuItem getMenuLoadDataSet() {
        return menuLoadDataSet;
    }

    public javax.swing.JMenuItem getMenuLoadMLP() {
        return menuLoadMLP;
    }

    public javax.swing.JMenuItem getMenuManual() {
        return menuManual;
    }

    public javax.swing.JMenuItem getMenuNewMLP() {
        return menuNewMLP;
    }

    public javax.swing.JMenuItem getMenuReset() {
        return menuReset;
    }

    public javax.swing.JMenuItem getMenuSaveDataSet() {
        return menuSaveDataSet;
    }

    public javax.swing.JMenuItem getMenuSaveMLP() {
        return menuSaveMLP;
    }

    public javax.swing.JMenuItem getMenuSubsampling() {
        return menuSubsampling;
    }

    public javax.swing.JMenuItem getMenuTrain() {
        return menuTrain;
    }

    public javax.swing.JPopupMenu getPopupNeuralNetwork() {
        return popupNeuralNetwork;
    }

    public javax.swing.JTable getTableWeights() {
        return tableWeights;
    }

    public javax.swing.JButton getToolLoadDataSet() {
        return toolLoadDataSet;
    }

    public javax.swing.JButton getToolLoadMLP() {
        return toolLoadMLP;
    }

    public javax.swing.JButton getToolNewMLP() {
        return toolNewMLP;
    }

    public javax.swing.JButton getToolSaveDataSet() {
        return toolSaveDataSet;
    }

    public javax.swing.JButton getToolSaveMLP() {
        return toolSaveMLP;
    }

    public javax.swing.JTree getTreeNeuralNetwork() {
        return treeNeuralNetwork;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupNeuralNetwork = new javax.swing.JPopupMenu();
        menuSubsampling = new javax.swing.JMenuItem();
        menuClassify = new javax.swing.JMenuItem();
        jSeparator4 = new javax.swing.JSeparator();
        menuTrain = new javax.swing.JMenuItem();
        menuReset = new javax.swing.JMenuItem();
        jSeparator5 = new javax.swing.JSeparator();
        menuChooseRandomTrainingTestData = new javax.swing.JMenuItem();
        menuSetAsNotUsed = new javax.swing.JMenuItem();
        menuSetAsTrainingData = new javax.swing.JMenuItem();
        menuSetAsTestData = new javax.swing.JMenuItem();
        jSeparator6 = new javax.swing.JSeparator();
        menuAdd = new javax.swing.JMenuItem();
        menuEdit = new javax.swing.JMenuItem();
        menuRemove = new javax.swing.JMenuItem();
        jSeparator7 = new javax.swing.JSeparator();
        menuRefresh = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        toolNewMLP = new javax.swing.JButton();
        toolLoadMLP = new javax.swing.JButton();
        toolSaveMLP = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JToolBar.Separator();
        toolLoadDataSet = new javax.swing.JButton();
        toolSaveDataSet = new javax.swing.JButton();
        jSeparator3 = new javax.swing.JToolBar.Separator();
        toolImportImages = new javax.swing.JButton();
        toolImportAudio = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeNeuralNetwork = new javax.swing.JTree();
        tabs = new javax.swing.JTabbedPane();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableWeights = new javax.swing.JTable();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane5 = new javax.swing.JScrollPane();
        labelWeightsImage = new yaprnn.gui.ImagePanel();
        jLabel7 = new javax.swing.JLabel();
        optionZoom1 = new javax.swing.JComboBox();
        jLabel8 = new javax.swing.JLabel();
        optionGamma = new javax.swing.JSlider();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        labelFilename = new javax.swing.JTextField();
        labelUsedSubsamplingOptions = new javax.swing.JTextField();
        labelSampleLabel = new javax.swing.JTextField();
        jPanel7 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        labelPreview = new yaprnn.gui.ImagePanel();
        jScrollPane4 = new javax.swing.JScrollPane();
        labelPreviewSubsampled = new yaprnn.gui.ImagePanel();
        jLabel4 = new javax.swing.JLabel();
        optionZoom2 = new javax.swing.JComboBox();
        jLabel5 = new javax.swing.JLabel();
        optionResolution = new javax.swing.JSpinner();
        jLabel6 = new javax.swing.JLabel();
        optionOverlap = new javax.swing.JSpinner();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNewMLP = new javax.swing.JMenuItem();
        menuLoadMLP = new javax.swing.JMenuItem();
        menuSaveMLP = new javax.swing.JMenuItem();
        jSeperator1 = new javax.swing.JSeparator();
        menuLoadDataSet = new javax.swing.JMenuItem();
        menuSaveDataSet = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        menuImportImages = new javax.swing.JMenuItem();
        menuImportAudio = new javax.swing.JMenuItem();
        jSeperator3 = new javax.swing.JSeparator();
        menuExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuManual = new javax.swing.JMenuItem();
        menuWebsite = new javax.swing.JMenuItem();

        menuSubsampling.setText("Subsampling");
        popupNeuralNetwork.add(menuSubsampling);

        menuClassify.setText("Classify");
        menuClassify.setActionCommand("Set Layer #");
        popupNeuralNetwork.add(menuClassify);
        popupNeuralNetwork.add(jSeparator4);

        menuTrain.setText("Train");
        popupNeuralNetwork.add(menuTrain);

        menuReset.setText("Reset");
        popupNeuralNetwork.add(menuReset);
        popupNeuralNetwork.add(jSeparator5);

        menuChooseRandomTrainingTestData.setText("Choose random training/test sets");
        popupNeuralNetwork.add(menuChooseRandomTrainingTestData);

        menuSetAsNotUsed.setText("Set as not used");
        popupNeuralNetwork.add(menuSetAsNotUsed);

        menuSetAsTrainingData.setText("Set as training data");
        popupNeuralNetwork.add(menuSetAsTrainingData);

        menuSetAsTestData.setText("Set as test data");
        popupNeuralNetwork.add(menuSetAsTestData);
        popupNeuralNetwork.add(jSeparator6);

        menuAdd.setText("Add");
        popupNeuralNetwork.add(menuAdd);

        menuEdit.setText("Edit");
        popupNeuralNetwork.add(menuEdit);

        menuRemove.setText("Remove");
        popupNeuralNetwork.add(menuRemove);
        popupNeuralNetwork.add(jSeparator7);

        menuRefresh.setText("Refresh");
        popupNeuralNetwork.add(menuRefresh);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YAPRNN");
        setBounds(new java.awt.Rectangle(0, 0, 600, 400));

        jToolBar1.setRollover(true);

        toolNewMLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconNewMLP.png"))); // NOI18N
        toolNewMLP.setText("New MLP");
        toolNewMLP.setFocusable(false);
        toolNewMLP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(toolNewMLP);

        toolLoadMLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconLoadMLP.png"))); // NOI18N
        toolLoadMLP.setText("Load MLP");
        toolLoadMLP.setFocusable(false);
        toolLoadMLP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(toolLoadMLP);

        toolSaveMLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconSaveMLP.png"))); // NOI18N
        toolSaveMLP.setText("Save MLP");
        toolSaveMLP.setFocusable(false);
        toolSaveMLP.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(toolSaveMLP);
        jToolBar1.add(jSeparator1);

        toolLoadDataSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconLoadDataSet.png"))); // NOI18N
        toolLoadDataSet.setText("Load dataset");
        toolLoadDataSet.setFocusable(false);
        toolLoadDataSet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(toolLoadDataSet);

        toolSaveDataSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconSaveDataSet.png"))); // NOI18N
        toolSaveDataSet.setText("Save dataset");
        toolSaveDataSet.setFocusable(false);
        toolSaveDataSet.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(toolSaveDataSet);
        jToolBar1.add(jSeparator3);

        toolImportImages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconLoadImage.png"))); // NOI18N
        toolImportImages.setText("Import images");
        toolImportImages.setFocusable(false);
        toolImportImages.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(toolImportImages);

        toolImportAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconLoadAudio.png"))); // NOI18N
        toolImportAudio.setText("Import audio");
        toolImportAudio.setFocusable(false);
        toolImportAudio.setHorizontalTextPosition(javax.swing.SwingConstants.RIGHT);
        jToolBar1.add(toolImportAudio);

        getContentPane().add(jToolBar1, java.awt.BorderLayout.NORTH);

        jSplitPane1.setDividerLocation(300);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Networks/Datasets"));

        treeNeuralNetwork.setComponentPopupMenu(popupNeuralNetwork);
        treeNeuralNetwork.setModel(null);
        treeNeuralNetwork.setRootVisible(false);
        treeNeuralNetwork.setShowsRootHandles(true);
        jScrollPane1.setViewportView(treeNeuralNetwork);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 457, Short.MAX_VALUE)
        );

        jSplitPane1.setLeftComponent(jPanel1);

        tableWeights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {

            }
        ));
        tableWeights.setAutoResizeMode(javax.swing.JTable.AUTO_RESIZE_OFF);
        tableWeights.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tableWeights);

        jTabbedPane1.addTab("Matrix", jScrollPane2);

        jPanel3.setOpaque(false);

        javax.swing.GroupLayout labelWeightsImageLayout = new javax.swing.GroupLayout(labelWeightsImage);
        labelWeightsImage.setLayout(labelWeightsImageLayout);
        labelWeightsImageLayout.setHorizontalGroup(
            labelWeightsImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 401, Short.MAX_VALUE)
        );
        labelWeightsImageLayout.setVerticalGroup(
            labelWeightsImageLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 368, Short.MAX_VALUE)
        );

        jScrollPane5.setViewportView(labelWeightsImage);

        jLabel7.setText("Zoom:");

        optionZoom1.setEditable(true);
        optionZoom1.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5", "1.0", "2.0", "4.0", "8.0", "16.0" }));
        optionZoom1.setSelectedIndex(1);

        jLabel8.setText("Gamma:");

        optionGamma.setMajorTickSpacing(5000);
        optionGamma.setMaximum(10000);
        optionGamma.setMinorTickSpacing(1000);
        optionGamma.setPaintTicks(true);
        optionGamma.setValue(5000);
        optionGamma.setOpaque(false);
        optionGamma.setValueIsAdjusting(true);

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 403, Short.MAX_VALUE)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jLabel7)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionZoom1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(jLabel8)
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                        .addComponent(optionGamma, javax.swing.GroupLayout.DEFAULT_SIZE, 255, Short.MAX_VALUE)))
                .addContainerGap())
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel7)
                        .addComponent(optionZoom1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addComponent(jLabel8))
                    .addComponent(optionGamma, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane5, javax.swing.GroupLayout.DEFAULT_SIZE, 370, Short.MAX_VALUE)
                .addContainerGap())
        );

        jTabbedPane1.addTab("Image", jPanel3);

        tabs.addTab("Layer details", jTabbedPane1);

        jPanel5.setOpaque(false);

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional informations"));
        jPanel6.setOpaque(false);

        jLabel1.setText("Filename:");

        jLabel2.setText("Sample label:");

        jLabel3.setText("Used subsampling options:");

        labelFilename.setEditable(false);
        labelFilename.setText("...");
        labelFilename.setBorder(null);
        labelFilename.setOpaque(false);

        labelUsedSubsamplingOptions.setEditable(false);
        labelUsedSubsamplingOptions.setText("...");
        labelUsedSubsamplingOptions.setBorder(null);
        labelUsedSubsamplingOptions.setOpaque(false);

        labelSampleLabel.setEditable(false);
        labelSampleLabel.setText("...");
        labelSampleLabel.setBorder(null);
        labelSampleLabel.setOpaque(false);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel1)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelFilename, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(labelSampleLabel, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)
                    .addComponent(labelUsedSubsamplingOptions, javax.swing.GroupLayout.DEFAULT_SIZE, 261, Short.MAX_VALUE)))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(labelFilename, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelSampleLabel, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelUsedSubsamplingOptions, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Preview"));
        jPanel7.setOpaque(false);

        jSplitPane2.setDividerLocation(225);

        javax.swing.GroupLayout labelPreviewLayout = new javax.swing.GroupLayout(labelPreview);
        labelPreview.setLayout(labelPreviewLayout);
        labelPreviewLayout.setHorizontalGroup(
            labelPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 222, Short.MAX_VALUE)
        );
        labelPreviewLayout.setVerticalGroup(
            labelPreviewLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jScrollPane3.setViewportView(labelPreview);

        jSplitPane2.setLeftComponent(jScrollPane3);

        javax.swing.GroupLayout labelPreviewSubsampledLayout = new javax.swing.GroupLayout(labelPreviewSubsampled);
        labelPreviewSubsampled.setLayout(labelPreviewSubsampledLayout);
        labelPreviewSubsampledLayout.setHorizontalGroup(
            labelPreviewSubsampledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 159, Short.MAX_VALUE)
        );
        labelPreviewSubsampledLayout.setVerticalGroup(
            labelPreviewSubsampledLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 287, Short.MAX_VALUE)
        );

        jScrollPane4.setViewportView(labelPreviewSubsampled);

        jSplitPane2.setRightComponent(jScrollPane4);

        jLabel4.setText("Zoom:");

        optionZoom2.setEditable(true);
        optionZoom2.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "0.5", "1.0", "2.0", "4.0", "8.0", "16.0" }));
        optionZoom2.setSelectedIndex(1);

        jLabel5.setText("Resolution:");

        optionResolution.setModel(new javax.swing.SpinnerNumberModel(16, 1, 256, 1));

        jLabel6.setText("Overlap:");

        optionOverlap.setModel(new javax.swing.SpinnerNumberModel(0.5d, 0.0d, 0.95d, 0.05d));

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addComponent(jLabel4)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionZoom2, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 41, Short.MAX_VALUE)
                .addComponent(jLabel5)
                .addGap(2, 2, 2)
                .addComponent(optionResolution, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel6)
                .addGap(4, 4, 4)
                .addComponent(optionOverlap, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE))
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 392, Short.MAX_VALUE)
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(optionZoom2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel5)
                    .addComponent(optionResolution, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel6)
                    .addComponent(optionOverlap, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 291, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jPanel7, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(jPanel6, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        tabs.addTab("Data sample details", jPanel5);

        jSplitPane1.setRightComponent(tabs);

        getContentPane().add(jSplitPane1, java.awt.BorderLayout.CENTER);

        jMenu1.setText("File");

        menuNewMLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconNewMLP.png"))); // NOI18N
        menuNewMLP.setMnemonic('N');
        menuNewMLP.setText("New MLP");
        jMenu1.add(menuNewMLP);

        menuLoadMLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconLoadMLP.png"))); // NOI18N
        menuLoadMLP.setMnemonic('L');
        menuLoadMLP.setText("Load MLP");
        jMenu1.add(menuLoadMLP);

        menuSaveMLP.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconSaveMLP.png"))); // NOI18N
        menuSaveMLP.setMnemonic('S');
        menuSaveMLP.setText("Save MLP");
        jMenu1.add(menuSaveMLP);
        jMenu1.add(jSeperator1);

        menuLoadDataSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconLoadDataSet.png"))); // NOI18N
        menuLoadDataSet.setMnemonic('D');
        menuLoadDataSet.setText("Load data set");
        jMenu1.add(menuLoadDataSet);

        menuSaveDataSet.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconSaveDataSet.png"))); // NOI18N
        menuSaveDataSet.setMnemonic('V');
        menuSaveDataSet.setText("Save data set");
        jMenu1.add(menuSaveDataSet);
        jMenu1.add(jSeparator2);

        menuImportImages.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconLoadImage.png"))); // NOI18N
        menuImportImages.setText("Import images");
        jMenu1.add(menuImportImages);

        menuImportAudio.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconLoadAudio.png"))); // NOI18N
        menuImportAudio.setText("Import audio");
        jMenu1.add(menuImportAudio);
        jMenu1.add(jSeperator3);

        menuExit.setIcon(new javax.swing.ImageIcon(getClass().getResource("/yaprnn/gui/view/iconExit.png"))); // NOI18N
        menuExit.setMnemonic('x');
        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        menuManual.setText("Manual");
        jMenu3.add(menuManual);

        menuWebsite.setText("Website");
        jMenu3.add(menuWebsite);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JScrollPane jScrollPane5;
    private javax.swing.JToolBar.Separator jSeparator1;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JToolBar.Separator jSeparator3;
    private javax.swing.JSeparator jSeparator4;
    private javax.swing.JSeparator jSeparator5;
    private javax.swing.JSeparator jSeparator6;
    private javax.swing.JSeparator jSeparator7;
    private javax.swing.JSeparator jSeperator1;
    private javax.swing.JSeparator jSeperator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JTextField labelFilename;
    private yaprnn.gui.ImagePanel labelPreview;
    private yaprnn.gui.ImagePanel labelPreviewSubsampled;
    private javax.swing.JTextField labelSampleLabel;
    private javax.swing.JTextField labelUsedSubsamplingOptions;
    private yaprnn.gui.ImagePanel labelWeightsImage;
    private javax.swing.JMenuItem menuAdd;
    private javax.swing.JMenuItem menuChooseRandomTrainingTestData;
    private javax.swing.JMenuItem menuClassify;
    private javax.swing.JMenuItem menuEdit;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuImportAudio;
    private javax.swing.JMenuItem menuImportImages;
    private javax.swing.JMenuItem menuLoadDataSet;
    private javax.swing.JMenuItem menuLoadMLP;
    private javax.swing.JMenuItem menuManual;
    private javax.swing.JMenuItem menuNewMLP;
    private javax.swing.JMenuItem menuRefresh;
    private javax.swing.JMenuItem menuRemove;
    private javax.swing.JMenuItem menuReset;
    private javax.swing.JMenuItem menuSaveDataSet;
    private javax.swing.JMenuItem menuSaveMLP;
    private javax.swing.JMenuItem menuSetAsNotUsed;
    private javax.swing.JMenuItem menuSetAsTestData;
    private javax.swing.JMenuItem menuSetAsTrainingData;
    private javax.swing.JMenuItem menuSubsampling;
    private javax.swing.JMenuItem menuTrain;
    private javax.swing.JMenuItem menuWebsite;
    private javax.swing.JSlider optionGamma;
    private javax.swing.JSpinner optionOverlap;
    private javax.swing.JSpinner optionResolution;
    private javax.swing.JComboBox optionZoom1;
    private javax.swing.JComboBox optionZoom2;
    private javax.swing.JPopupMenu popupNeuralNetwork;
    private javax.swing.JTable tableWeights;
    private javax.swing.JTabbedPane tabs;
    private javax.swing.JButton toolImportAudio;
    private javax.swing.JButton toolImportImages;
    private javax.swing.JButton toolLoadDataSet;
    private javax.swing.JButton toolLoadMLP;
    private javax.swing.JButton toolNewMLP;
    private javax.swing.JButton toolSaveDataSet;
    private javax.swing.JButton toolSaveMLP;
    private javax.swing.JTree treeNeuralNetwork;
    // End of variables declaration//GEN-END:variables
}
