package yaprnn.gui.view;

public class MainView extends javax.swing.JFrame {
  
    /**
	 * Autogenerated serialization ID 
	 */
	private static final long serialVersionUID = -3378803686681357347L;
	
	/** Creates new form MainView */
    public MainView() {
        initComponents();
    }

    public javax.swing.JLabel getLabelFilename() {
        return labelFilename;
    }

    public javax.swing.JLabel getLabelNeuralNetworkEditable() {
        return labelNeuralNetworkEditable;
    }

    public javax.swing.JLabel getLabelSampleLabel() {
        return labelSampleLabel;
    }

    public javax.swing.JLabel getLabelSubsamplingAfter() {
        return labelSubsamplingAfter;
    }

    public javax.swing.JLabel getLabelSubsamplingBefore() {
        return labelSubsamplingBefore;
    }

    public javax.swing.JLabel getLabelUsedSubsamplingOptions() {
        return labelUsedSubsamplingOptions;
    }

    public javax.swing.JMenuItem getMenuClassify() {
        return menuClassify;
    }

    public javax.swing.JMenuItem getMenuExit() {
        return menuExit;
    }

    public javax.swing.JMenuItem getMenuImportAudio() {
        return menuImportAudio;
    }

    public javax.swing.JMenuItem getMenuImportAudio2() {
        return menuImportAudio2;
    }

    public javax.swing.JMenuItem getMenuImportImage() {
        return menuImportImage;
    }

    public javax.swing.JMenuItem getMenuImportImage2() {
        return menuImportImage2;
    }

    public javax.swing.JMenuItem getMenuLoadDataSet() {
        return menuLoadDataSet;
    }

    public javax.swing.JMenuItem getMenuLoadMLP() {
        return menuLoadMLP;
    }

    public javax.swing.JMenuItem getMenuManual() {
        return menuManual;
    }

    public javax.swing.JMenuItem getMenuNewMLP() {
        return menuNewMLP;
    }

    public javax.swing.JMenuItem getMenuResetNetwork() {
        return menuResetNetwork;
    }

    public javax.swing.JMenuItem getMenuSaveDataSet() {
        return menuSaveDataSet;
    }

    public javax.swing.JMenuItem getMenuSaveMLP() {
        return menuSaveMLP;
    }

    public javax.swing.JMenuItem getMenuSubsampling() {
        return menuSubsampling;
    }

    public javax.swing.JMenuItem getMenuTraining() {
        return menuTraining;
    }

    public javax.swing.JComboBox getOptionWeightInit() {
        return optionWeightInit;
    }

    public javax.swing.JPopupMenu getPopupImport() {
        return popupImport;
    }

    public javax.swing.JPopupMenu getPopupNeuralNetwork() {
        return popupNeuralNetwork;
    }

    public javax.swing.JTable getTableWeights() {
        return tableWeights;
    }

    public javax.swing.JButton getToolImport() {
        return toolImport;
    }

    public javax.swing.JButton getToolLoadDataSet() {
        return toolLoadDataSet;
    }

    public javax.swing.JButton getToolLoadMLP() {
        return toolLoadMLP;
    }

    public javax.swing.JButton getToolNewMLP() {
        return toolNewMLP;
    }

    public javax.swing.JButton getToolSaveDataSet() {
        return toolSaveDataSet;
    }

    public javax.swing.JButton getToolSaveMLP() {
        return toolSaveMLP;
    }

    public javax.swing.JTree getTreeNeuralNetwork() {
        return treeNeuralNetwork;
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupNeuralNetwork = new javax.swing.JPopupMenu();
        menuClassify = new javax.swing.JMenuItem();
        menuTraining = new javax.swing.JMenuItem();
        menuSubsampling = new javax.swing.JMenuItem();
        menuResetNetwork = new javax.swing.JMenuItem();
        popupImport = new javax.swing.JPopupMenu();
        menuImportImage2 = new javax.swing.JMenuItem();
        menuImportAudio2 = new javax.swing.JMenuItem();
        jToolBar1 = new javax.swing.JToolBar();
        toolNewMLP = new javax.swing.JButton();
        toolLoadMLP = new javax.swing.JButton();
        toolSaveMLP = new javax.swing.JButton();
        toolLoadDataSet = new javax.swing.JButton();
        toolSaveDataSet = new javax.swing.JButton();
        toolImport = new javax.swing.JButton();
        jSplitPane1 = new javax.swing.JSplitPane();
        jPanel1 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        treeNeuralNetwork = new javax.swing.JTree();
        optionWeightInit = new javax.swing.JComboBox();
        jLabel1 = new javax.swing.JLabel();
        labelNeuralNetworkEditable = new javax.swing.JLabel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel2 = new javax.swing.JPanel();
        jPanel3 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tableWeights = new javax.swing.JTable();
        jPanel5 = new javax.swing.JPanel();
        jPanel6 = new javax.swing.JPanel();
        jSplitPane2 = new javax.swing.JSplitPane();
        jScrollPane3 = new javax.swing.JScrollPane();
        labelSubsamplingBefore = new javax.swing.JLabel();
        jScrollPane4 = new javax.swing.JScrollPane();
        labelSubsamplingAfter = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelFilename = new javax.swing.JLabel();
        labelSampleLabel = new javax.swing.JLabel();
        labelUsedSubsamplingOptions = new javax.swing.JLabel();
        jMenuBar1 = new javax.swing.JMenuBar();
        jMenu1 = new javax.swing.JMenu();
        menuNewMLP = new javax.swing.JMenuItem();
        menuLoadMLP = new javax.swing.JMenuItem();
        menuSaveMLP = new javax.swing.JMenuItem();
        jSeperator1 = new javax.swing.JSeparator();
        menuLoadDataSet = new javax.swing.JMenuItem();
        menuSaveDataSet = new javax.swing.JMenuItem();
        jSeparator2 = new javax.swing.JSeparator();
        jMenu2 = new javax.swing.JMenu();
        menuImportImage = new javax.swing.JMenuItem();
        menuImportAudio = new javax.swing.JMenuItem();
        jSeperator3 = new javax.swing.JSeparator();
        menuExit = new javax.swing.JMenuItem();
        jMenu3 = new javax.swing.JMenu();
        menuManual = new javax.swing.JMenuItem();

        menuClassify.setText("Classify Data");
        menuClassify.setActionCommand("Set Layer #");
        menuClassify.setEnabled(false);
        popupNeuralNetwork.add(menuClassify);

        menuTraining.setText("Train MLP");
        menuTraining.setEnabled(false);
        popupNeuralNetwork.add(menuTraining);

        menuSubsampling.setText("Subsampling");
        menuSubsampling.setEnabled(false);
        popupNeuralNetwork.add(menuSubsampling);

        menuResetNetwork.setText("Reset Network");
        menuResetNetwork.setEnabled(false);
        popupNeuralNetwork.add(menuResetNetwork);

        menuImportImage2.setText("Import Image Data");
        popupImport.add(menuImportImage2);

        menuImportAudio2.setText("Import Audio Data");
        popupImport.add(menuImportAudio2);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setTitle("YAPRNN");
        setBounds(new java.awt.Rectangle(0, 0, 600, 400));

        toolNewMLP.setText("New MLP");
        toolNewMLP.setToolTipText("New MLP");
        toolNewMLP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolNewMLP.setPreferredSize(new java.awt.Dimension(45, 45));
        jToolBar1.add(toolNewMLP);

        toolLoadMLP.setText("Load MLP");
        toolLoadMLP.setToolTipText("Load MLP");
        toolLoadMLP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBar1.add(toolLoadMLP);

        toolSaveMLP.setText("Save MLP");
        toolSaveMLP.setToolTipText("Save MLP");
        toolSaveMLP.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolSaveMLP.setPreferredSize(new java.awt.Dimension(45, 45));
        jToolBar1.add(toolSaveMLP);

        toolLoadDataSet.setText("Load dataset");
        toolLoadDataSet.setToolTipText("Load Data Set");
        toolLoadDataSet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        jToolBar1.add(toolLoadDataSet);

        toolSaveDataSet.setText("Save Dataset");
        toolSaveDataSet.setToolTipText("Save Data Set");
        toolSaveDataSet.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolSaveDataSet.setPreferredSize(new java.awt.Dimension(45, 45));
        jToolBar1.add(toolSaveDataSet);

        toolImport.setText("Import");
        toolImport.setToolTipText("Import Audio / Image Data");
        toolImport.setFocusable(false);
        toolImport.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);
        toolImport.setPreferredSize(new java.awt.Dimension(45, 45));
        jToolBar1.add(toolImport);

        jSplitPane1.setDividerLocation(300);

        jPanel1.setBorder(javax.swing.BorderFactory.createTitledBorder("Neural Network"));

        treeNeuralNetwork.setComponentPopupMenu(popupNeuralNetwork);
        treeNeuralNetwork.setModel(null);
        treeNeuralNetwork.setRootVisible(false);
        treeNeuralNetwork.setShowsRootHandles(true);
        jScrollPane1.setViewportView(treeNeuralNetwork);

        optionWeightInit.setModel(new javax.swing.DefaultComboBoxModel(new String[] { "Autoencoder", "Random" }));
        optionWeightInit.setEnabled(false);

        jLabel1.setText("Weight Initialization:");

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addComponent(labelNeuralNetworkEditable)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(optionWeightInit, 0, 175, Short.MAX_VALUE))
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 283, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(jLabel1)
                        .addComponent(optionWeightInit, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(labelNeuralNetworkEditable))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 477, Short.MAX_VALUE))
        );

        jSplitPane1.setLeftComponent(jPanel1);

        jPanel2.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel3.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional Information"));

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 455, Short.MAX_VALUE)
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 0, Short.MAX_VALUE)
        );

        jPanel4.setBorder(javax.swing.BorderFactory.createTitledBorder("Weights"));

        tableWeights.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {},
                {},
                {}
            },
            new String [] {

            }
        ));
        tableWeights.setRowSelectionAllowed(false);
        jScrollPane2.setViewportView(tableWeights);

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 423, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel3, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addComponent(jPanel3, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Layer Details", jPanel2);

        jPanel5.setBorder(javax.swing.BorderFactory.createTitledBorder(""));

        jPanel6.setBorder(javax.swing.BorderFactory.createTitledBorder("Sample details"));

        jScrollPane3.setViewportView(labelSubsamplingBefore);

        jSplitPane2.setLeftComponent(jScrollPane3);

        jScrollPane4.setViewportView(labelSubsamplingAfter);

        jSplitPane2.setRightComponent(jScrollPane4);

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 455, Short.MAX_VALUE)
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jSplitPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 369, Short.MAX_VALUE)
        );

        jPanel7.setBorder(javax.swing.BorderFactory.createTitledBorder("Additional informations"));

        jLabel2.setText("Filename:");

        jLabel3.setText("Sample label:");

        jLabel4.setText("Used subsampling options:");

        labelFilename.setText("...");

        labelSampleLabel.setText("...");

        labelUsedSubsamplingOptions.setText("...");

        javax.swing.GroupLayout jPanel7Layout = new javax.swing.GroupLayout(jPanel7);
        jPanel7.setLayout(jPanel7Layout);
        jPanel7Layout.setHorizontalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel2)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(labelSampleLabel)
                    .addComponent(labelUsedSubsamplingOptions)
                    .addComponent(labelFilename))
                .addContainerGap(310, Short.MAX_VALUE))
        );
        jPanel7Layout.setVerticalGroup(
            jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel7Layout.createSequentialGroup()
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(labelFilename))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(labelSampleLabel))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel7Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel4)
                    .addComponent(labelUsedSubsamplingOptions)))
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel7, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel7, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("Data Sample Details", jPanel5);

        jSplitPane1.setRightComponent(jTabbedPane1);

        jMenu1.setText("File");

        menuNewMLP.setMnemonic('N');
        menuNewMLP.setText("New MLP");
        jMenu1.add(menuNewMLP);

        menuLoadMLP.setMnemonic('L');
        menuLoadMLP.setText("Load MLP");
        jMenu1.add(menuLoadMLP);

        menuSaveMLP.setMnemonic('S');
        menuSaveMLP.setText("Save MLP");
        jMenu1.add(menuSaveMLP);
        jMenu1.add(jSeperator1);

        menuLoadDataSet.setMnemonic('D');
        menuLoadDataSet.setText("Load Data Set");
        jMenu1.add(menuLoadDataSet);

        menuSaveDataSet.setMnemonic('V');
        menuSaveDataSet.setText("Save Data Set");
        jMenu1.add(menuSaveDataSet);
        jMenu1.add(jSeparator2);

        jMenu2.setText("Import");

        menuImportImage.setText("Image Data");
        jMenu2.add(menuImportImage);

        menuImportAudio.setText("Audio Data");
        jMenu2.add(menuImportAudio);

        jMenu1.add(jMenu2);
        jMenu1.add(jSeperator3);

        menuExit.setMnemonic('x');
        menuExit.setText("Exit");
        jMenu1.add(menuExit);

        jMenuBar1.add(jMenu1);

        jMenu3.setText("Help");

        menuManual.setText("Manual");
        jMenu3.add(menuManual);

        jMenuBar1.add(jMenu3);

        setJMenuBar(jMenuBar1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jToolBar1, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
            .addComponent(jSplitPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 798, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jToolBar1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSplitPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 535, Short.MAX_VALUE))
        );

        getAccessibleContext().setAccessibleName("");

        pack();
    }// </editor-fold>//GEN-END:initComponents

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JMenu jMenu1;
    private javax.swing.JMenu jMenu2;
    private javax.swing.JMenu jMenu3;
    private javax.swing.JMenuBar jMenuBar1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JScrollPane jScrollPane3;
    private javax.swing.JScrollPane jScrollPane4;
    private javax.swing.JSeparator jSeparator2;
    private javax.swing.JSeparator jSeperator1;
    private javax.swing.JSeparator jSeperator3;
    private javax.swing.JSplitPane jSplitPane1;
    private javax.swing.JSplitPane jSplitPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JLabel labelFilename;
    private javax.swing.JLabel labelNeuralNetworkEditable;
    private javax.swing.JLabel labelSampleLabel;
    private javax.swing.JLabel labelSubsamplingAfter;
    private javax.swing.JLabel labelSubsamplingBefore;
    private javax.swing.JLabel labelUsedSubsamplingOptions;
    private javax.swing.JMenuItem menuClassify;
    private javax.swing.JMenuItem menuExit;
    private javax.swing.JMenuItem menuImportAudio;
    private javax.swing.JMenuItem menuImportAudio2;
    private javax.swing.JMenuItem menuImportImage;
    private javax.swing.JMenuItem menuImportImage2;
    private javax.swing.JMenuItem menuLoadDataSet;
    private javax.swing.JMenuItem menuLoadMLP;
    private javax.swing.JMenuItem menuManual;
    private javax.swing.JMenuItem menuNewMLP;
    private javax.swing.JMenuItem menuResetNetwork;
    private javax.swing.JMenuItem menuSaveDataSet;
    private javax.swing.JMenuItem menuSaveMLP;
    private javax.swing.JMenuItem menuSubsampling;
    private javax.swing.JMenuItem menuTraining;
    private javax.swing.JComboBox optionWeightInit;
    private javax.swing.JPopupMenu popupImport;
    private javax.swing.JPopupMenu popupNeuralNetwork;
    private javax.swing.JTable tableWeights;
    private javax.swing.JButton toolImport;
    private javax.swing.JButton toolLoadDataSet;
    private javax.swing.JButton toolLoadMLP;
    private javax.swing.JButton toolNewMLP;
    private javax.swing.JButton toolSaveDataSet;
    private javax.swing.JButton toolSaveMLP;
    private javax.swing.JTree treeNeuralNetwork;
    // End of variables declaration//GEN-END:variables

}
